import type { Pet, Provider, SortOption } from "./types";

export const sortOptions: { value: SortOption; label: string }[] = [
  { value: "recommended", label: "Recommended" },
  { value: "rating", label: "Highest rated" },
  { value: "distance", label: "Nearest" },
  { value: "price-asc", label: "Price: Low to High" },
];

export const specialtiesByType: Record<Provider["type"], string[]> = {
  vet: [
    "Wellness exams",
    "Vaccinations",
    "Dermatology",
    "Emergency & critical care",
    "Exotic & avian medicine",
    "Dental & oral surgery",
  ],
  groomer: [
    "Breed-specific styling",
    "Large breed specialist",
    "Cat grooming",
    "Mobile grooming",
    "Show grooming",
    "De-shedding",
  ],
  trainer: [
    "Puppy foundations",
    "Obedience & recall",
    "Reactivity & anxiety",
    "Agility",
  ],
  sitter: [
    "In-home visits",
    "Overnight stays",
    "Dog walking",
    "Multi-pet households",
  ],
};

export const mockPets: Pet[] = [
  { id: "pet-1", name: "Biscuit", species: "Dog", breed: "Golden Retriever", initials: "BI" },
  { id: "pet-2", name: "Luna", species: "Cat", breed: "British Shorthair", initials: "LU" },
  { id: "pet-3", name: "Kiwi", species: "Small pet", breed: "Holland Lop Rabbit", initials: "KI" },
];

export const providers: Provider[] = [
  {
    id: "pr-01",
    slug: "dr-maya-reyes",
    type: "vet",
    name: "Dr. Maya Reyes",
    title: "DVM, Small Animal Medicine",
    clinicName: "Sunrise Animal Hospital",
    bio: "Dr. Reyes has spent over a decade helping anxious pets (and their anxious parents) through everything from routine checkups to tricky diagnoses. She's known for explaining things in plain English, not vet-speak.",
    initials: "MR",
    specialties: ["Wellness exams", "Vaccinations", "Dermatology"],
    rating: 4.9,
    reviewCount: 312,
    yearsExperience: 12,
    location: { city: "Portland", state: "OR", distanceMiles: 1.8 },
    languages: ["English", "Spanish"],
    acceptsNewPatients: true,
    verified: true,
    services: [
      { id: "svc-wellness", name: "Wellness exam", durationMinutes: 30, price: 10000 },
      { id: "svc-vaccination", name: "Vaccination", durationMinutes: 15, price: 600 },
      { id: "svc-video", name: "Video consult", durationMinutes: 20, price: 499 },
    ],
  },
  {
    id: "pr-02",
    slug: "dr-owen-park",
    type: "vet",
    name: "Dr. Owen Park",
    title: "DVM, Emergency & Critical Care",
    clinicName: "Northgate Veterinary ER",
    bio: "Board-certified in emergency medicine, Dr. Park has led overnight ER shifts for nine years. He specializes in fast, calm triage when minutes matter.",
    initials: "OP",
    specialties: ["Emergency & critical care", "Wellness exams"],
    rating: 4.8,
    reviewCount: 210,
    yearsExperience: 9,
    location: { city: "Portland", state: "OR", distanceMiles: 3.4 },
    languages: ["English", "Korean"],
    acceptsNewPatients: true,
    verified: true,
    services: [
      { id: "svc-sick", name: "Sick visit", durationMinutes: 30, price: 1200 },
      { id: "svc-emergency", name: "Emergency triage", durationMinutes: 45, price: 2500 },
    ],
  },
  {
    id: "pr-03",
    slug: "dr-priya-nair",
    type: "vet",
    name: "Dr. Priya Nair",
    title: "DVM, Exotic & Avian Medicine",
    clinicName: "Featherwell Clinic",
    bio: "One of the few exotic specialists in the area — Dr. Nair treats birds, reptiles, and small mammals with the same rigor most clinics reserve for cats and dogs.",
    initials: "PN",
    specialties: ["Exotic & avian medicine", "Wellness exams"],
    rating: 4.9,
    reviewCount: 145,
    yearsExperience: 15,
    location: { city: "Beaverton", state: "OR", distanceMiles: 6.1 },
    languages: ["English", "Hindi"],
    acceptsNewPatients: true,
    verified: true,
    services: [
      { id: "svc-exotic-exam", name: "Exotic wellness exam", durationMinutes: 30, price: 1000 },
      { id: "svc-video", name: "Video consult", durationMinutes: 20, price: 599 },
    ],
  },
  {
    id: "pr-04",
    slug: "dr-sam-whitfield",
    type: "vet",
    name: "Dr. Sam Whitfield",
    title: "DVM, General Practice",
    clinicName: "Willow Creek Vet Clinic",
    bio: "A generalist's generalist — Dr. Whitfield has been the family vet for half the neighborhood for the last seven years, from puppy shots to senior-pet care plans.",
    initials: "SW",
    specialties: ["Wellness exams", "Vaccinations"],
    rating: 4.7,
    reviewCount: 402,
    yearsExperience: 7,
    location: { city: "Portland", state: "OR", distanceMiles: 2.2 },
    languages: ["English"],
    acceptsNewPatients: true,
    verified: true,
    services: [
      { id: "svc-wellness", name: "Wellness exam", durationMinutes: 30, price: 9000 },
      { id: "svc-vaccination", name: "Vaccination", durationMinutes: 15, price: 450 },
      { id: "svc-sick", name: "Sick visit", durationMinutes: 30, price: 900 },
    ],
  },
  {
    id: "pr-05",
    slug: "dr-elena-cruz",
    type: "vet",
    name: "Dr. Elena Cruz",
    title: "DVM, Dermatology & Allergy",
    clinicName: "CalmPaws Dermatology",
    bio: "Dr. Cruz focuses exclusively on skin, coat, and allergy issues — the appointments other vets refer out when a rash or itch won't resolve.",
    initials: "EC",
    specialties: ["Dermatology", "Wellness exams"],
    rating: 4.8,
    reviewCount: 98,
    yearsExperience: 11,
    location: { city: "Lake Oswego", state: "OR", distanceMiles: 8.9 },
    languages: ["English", "Portuguese"],
    acceptsNewPatients: false,
    verified: true,
    services: [
      { id: "svc-derm", name: "Dermatology consult", durationMinutes: 40, price: 1500 },
      { id: "svc-video", name: "Video consult", durationMinutes: 20, price: 699 },
    ],
  },
  {
    id: "pr-06",
    slug: "dr-jordan-blake",
    type: "vet",
    name: "Dr. Jordan Blake",
    title: "DVM, Dental & Oral Surgery",
    clinicName: "BrightSmile Vet Dental",
    bio: "Dr. Blake trained specifically in veterinary dentistry and oral surgery — cleanings, extractions, and the occasional very confused cat.",
    initials: "JB",
    specialties: ["Dental & oral surgery", "Wellness exams"],
    rating: 4.9,
    reviewCount: 176,
    yearsExperience: 14,
    location: { city: "Portland", state: "OR", distanceMiles: 4.5 },
    languages: ["English"],
    acceptsNewPatients: true,
    verified: true,
    services: [
      { id: "svc-dental-exam", name: "Dental exam", durationMinutes: 30, price: 950 },
      { id: "svc-dental-clean", name: "Dental cleaning", durationMinutes: 60, price: 4500 },
    ],
  },
  {
    id: "pr-07",
    slug: "riley-chen",
    type: "groomer",
    name: "Riley Chen",
    title: "Certified Master Groomer",
    clinicName: "The Tidy Tail Studio",
    bio: "Riley has groomed everything from teacup poodles to St. Bernards over eight years, with a gentle-handling approach for nervous first-timers.",
    initials: "RC",
    specialties: ["Breed-specific styling", "De-shedding"],
    rating: 4.9,
    reviewCount: 520,
    yearsExperience: 8,
    location: { city: "Portland", state: "OR", distanceMiles: 1.2 },
    languages: ["English", "Mandarin"],
    acceptsNewPatients: true,
    verified: true,
    services: [
      { id: "svc-bath", name: "Bath & brush", durationMinutes: 45, price: 800 },
      { id: "svc-full-groom", name: "Full groom", durationMinutes: 90, price: 1500 },
      { id: "svc-nails", name: "Nail trim", durationMinutes: 15, price: 250 },
    ],
  },
  {
    id: "pr-08",
    slug: "sofia-martins",
    type: "groomer",
    name: "Sofia Martins",
    title: "Breed-Specific Styling Specialist",
    clinicName: "Fluff & Fold Grooming",
    bio: "Sofia specializes in show-standard breed cuts — Poodles, Bichons, Schnauzers — but takes just as much care with a scruffy rescue mutt.",
    initials: "SM",
    specialties: ["Breed-specific styling"],
    rating: 4.8,
    reviewCount: 340,
    yearsExperience: 6,
    location: { city: "Portland", state: "OR", distanceMiles: 2.7 },
    languages: ["English", "Portuguese"],
    acceptsNewPatients: true,
    verified: true,
    services: [
      { id: "svc-bath", name: "Bath & brush", durationMinutes: 45, price: 900 },
      { id: "svc-full-groom", name: "Full groom", durationMinutes: 90, price: 1700 },
    ],
  },
  {
    id: "pr-09",
    slug: "marcus-webb",
    type: "groomer",
    name: "Marcus Webb",
    title: "Large Breed Specialist",
    clinicName: "Big Dog Grooming Co.",
    bio: "Marcus built his studio specifically around big dogs — reinforced tables, wide tubs, and a lot of patience for 100+ lb clients.",
    initials: "MW",
    specialties: ["Large breed specialist", "De-shedding"],
    rating: 4.7,
    reviewCount: 289,
    yearsExperience: 10,
    location: { city: "Gresham", state: "OR", distanceMiles: 9.3 },
    languages: ["English"],
    acceptsNewPatients: true,
    verified: true,
    services: [
      { id: "svc-full-groom", name: "Full groom", durationMinutes: 90, price: 1400 },
      { id: "svc-deshed", name: "De-shed treatment", durationMinutes: 60, price: 1100 },
    ],
  },
  {
    id: "pr-10",
    slug: "ava-thompson",
    type: "groomer",
    name: "Ava Thompson",
    title: "Cat Grooming Specialist",
    clinicName: "Whisker Works",
    bio: "A rare cat-only groomer — Ava's studio is deliberately quiet and dog-free, built around a slower, low-stress process for feline clients.",
    initials: "AT",
    specialties: ["Cat grooming"],
    rating: 4.9,
    reviewCount: 156,
    yearsExperience: 5,
    location: { city: "Portland", state: "OR", distanceMiles: 3.1 },
    languages: ["English"],
    acceptsNewPatients: true,
    verified: true,
    services: [
      { id: "svc-cat-bath", name: "Cat bath & brush", durationMinutes: 40, price: 950 },
      { id: "svc-cat-nails", name: "Nail trim", durationMinutes: 15, price: 300 },
    ],
  },
  {
    id: "pr-11",
    slug: "diego-fernandez",
    type: "groomer",
    name: "Diego Fernandez",
    title: "Mobile Grooming",
    clinicName: "Pawmobile Grooming",
    bio: "Diego brings a fully equipped grooming van to your driveway — ideal for multi-pet households or pets who get carsick before they even leave the yard.",
    initials: "DF",
    specialties: ["Mobile grooming"],
    rating: 4.8,
    reviewCount: 410,
    yearsExperience: 9,
    location: { city: "Portland", state: "OR", distanceMiles: 0 },
    languages: ["English", "Spanish"],
    acceptsNewPatients: true,
    verified: true,
    services: [
      { id: "svc-bath", name: "Bath & brush", durationMinutes: 45, price: 1300 },
      { id: "svc-full-groom", name: "Full groom", durationMinutes: 90, price: 2200 },
    ],
  },
  {
    id: "pr-12",
    slug: "noor-hassan",
    type: "groomer",
    name: "Noor Hassan",
    title: "Show Dog Grooming",
    clinicName: "Prestige Pet Styling",
    bio: "Noor has prepped dogs ring-side for over a decade of conformation shows — precision styling for handlers who need it exactly right.",
    initials: "NH",
    specialties: ["Show grooming", "Breed-specific styling"],
    rating: 4.9,
    reviewCount: 88,
    yearsExperience: 12,
    location: { city: "Lake Oswego", state: "OR", distanceMiles: 7.6 },
    languages: ["English", "Arabic"],
    acceptsNewPatients: false,
    verified: true,
    services: [
      { id: "svc-show-groom", name: "Show groom", durationMinutes: 120, price: 3500 },
      { id: "svc-full-groom", name: "Full groom", durationMinutes: 90, price: 1800 },
    ],
  },
  {
    id: "pr-13",
    slug: "casey-nguyen",
    type: "trainer",
    name: "Casey Nguyen",
    title: "Certified Professional Dog Trainer",
    clinicName: "Steady Paws Training",
    bio: "Casey builds obedience programs around positive reinforcement — puppy foundations through recall work for dogs who've learned to tune owners out.",
    initials: "CN",
    specialties: ["Puppy foundations", "Obedience & recall"],
    rating: 4.9,
    reviewCount: 164,
    yearsExperience: 9,
    location: { city: "Portland", state: "OR", distanceMiles: 2.4 },
    languages: ["English", "Vietnamese"],
    acceptsNewPatients: true,
    verified: true,
    services: [
      { id: "svc-puppy-basics", name: "Puppy basics (4-week)", durationMinutes: 45, price: 4000 },
      { id: "svc-1-1-session", name: "1:1 training session", durationMinutes: 60, price: 900 },
    ],
  },
  {
    id: "pr-14",
    slug: "harper-reid",
    type: "trainer",
    name: "Harper Reid",
    title: "Behaviorist, Reactivity & Anxiety",
    clinicName: "Calm Companion Training",
    bio: "Harper works exclusively with reactive and anxious dogs — the ones other programs turn away — using a slow, structured desensitization approach.",
    initials: "HR",
    specialties: ["Reactivity & anxiety", "Obedience & recall"],
    rating: 4.8,
    reviewCount: 97,
    yearsExperience: 11,
    location: { city: "Beaverton", state: "OR", distanceMiles: 5.7 },
    languages: ["English"],
    acceptsNewPatients: true,
    verified: true,
    services: [
      { id: "svc-behavior-consult", name: "Behavior consult", durationMinutes: 60, price: 1500 },
      { id: "svc-6-week-program", name: "6-week reactivity program", durationMinutes: 60, price: 7500 },
    ],
  },
  {
    id: "pr-15",
    slug: "jamie-ortiz",
    type: "sitter",
    name: "Jamie Ortiz",
    title: "Background-Checked Pet Sitter",
    clinicName: "Homebody Pet Care",
    bio: "Jamie has sat for over 400 stays across the metro — daily visits, overnights, and everything a pet needs to stick to its routine while you're away.",
    initials: "JO",
    specialties: ["In-home visits", "Overnight stays", "Dog walking"],
    rating: 4.9,
    reviewCount: 233,
    yearsExperience: 6,
    location: { city: "Portland", state: "OR", distanceMiles: 1.6 },
    languages: ["English", "Spanish"],
    acceptsNewPatients: true,
    verified: true,
    services: [
      { id: "svc-drop-in", name: "30-min drop-in visit", durationMinutes: 30, price: 350 },
      { id: "svc-overnight", name: "Overnight stay", durationMinutes: 720, price: 6500 },
    ],
  },
  {
    id: "pr-16",
    slug: "priya-desai",
    type: "sitter",
    name: "Priya Desai",
    title: "Multi-Pet Household Specialist",
    clinicName: "Whisker Watch",
    bio: "Priya specializes in multi-pet homes — juggling feeding schedules, medications, and litter boxes for households other sitters find overwhelming.",
    initials: "PD",
    specialties: ["Multi-pet households", "In-home visits"],
    rating: 4.7,
    reviewCount: 118,
    yearsExperience: 5,
    location: { city: "Gresham", state: "OR", distanceMiles: 8.1 },
    languages: ["English", "Gujarati"],
    acceptsNewPatients: true,
    verified: true,
    services: [
      { id: "svc-drop-in", name: "30-min drop-in visit", durationMinutes: 30, price: 350 },
      { id: "svc-dog-walk", name: "30-min dog walk", durationMinutes: 30, price: 300 },
    ],
  },
];
