import {
  Bird,
  Cat,
  Dog,
  Droplet,
  Gamepad2,
  Home as HomeIcon,
  Leaf,
  Package,
  Rabbit,
  ShieldCheck,
  Syringe,
  Utensils,
  type LucideIcon,
} from "lucide-react";
import type { IconKey, PetType, PriceBucket, Product, ProductDetail, SortOption } from "./types";

/** Resolves a product's `iconKey` to its Lucide component — see the note on `IconKey` for why this indirection exists. */
export const productIcons: Record<IconKey, LucideIcon> = {
  home: HomeIcon,
  utensils: Utensils,
  gamepad: Gamepad2,
  shield: ShieldCheck,
  package: Package,
  leaf: Leaf,
  droplet: Droplet,
  syringe: Syringe,
};

export const petTypeLabels: Record<PetType, string> = {
  dogs: "Dogs",
  cats: "Cats",
  birds: "Birds",
  "small-pets": "Small pets",
  aquatics: "Aquatics",
};

export const petTypeIcons: Record<PetType, LucideIcon> = {
  dogs: Dog,
  cats: Cat,
  birds: Bird,
  "small-pets": Rabbit,
  aquatics: Droplet,
};

export const productCategories: string[] = [
  "Food & treats",
  "Toys & enrichment",
  "Beds & furniture",
  "Gear & accessories",
  "Health & wellness",
];

export const priceBuckets: PriceBucket[] = [
  { label: "Under ₹500", min: 0, max: 500 },
  { label: "₹500 – ₹1,500", min: 500, max: 1500 },
  { label: "₹1,500 – ₹5,000", min: 1500, max: 5000 },
  { label: "₹5,000+", min: 5000, max: null },
];

export const sortOptions: { value: SortOption; label: string }[] = [
  { value: "featured", label: "Featured" },
  { value: "price-asc", label: "Price: Low to High" },
  { value: "price-desc", label: "Price: High to Low" },
  { value: "rating", label: "Customer Rating" },
];

const shippingReturns: ProductDetail = {
  title: "Shipping & returns",
  content:
    "Free shipping on orders over ₹999. Delivered in 2–5 business days. Free returns within 30 days if it's not the right fit.",
};

export const products: Product[] = [
  {
    id: "p01",
    slug: "orthopedic-memory-foam-bed",
    name: "Orthopedic Memory Foam Bed",
    petType: "dogs",
    category: "Beds & furniture",
    price: 3499,
    originalPrice: 4999,
    rating: 4.8,
    reviewCount: 1204,
    badge: "Bestseller",
    iconKey: "home",
    description:
      "Joint-supporting memory foam with a machine-washable cover, sized for dogs who like to really sprawl out.",
    details: [
      { title: "Materials", content: "3-inch orthopedic memory foam base, water-resistant liner, removable machine-washable cover." },
      shippingReturns,
    ],
    inStock: true,
    rank: 1,
    variants: [
      { label: "Charcoal", swatchClassName: "from-foreground/40 via-foreground/10 to-transparent" },
      { label: "Sand", swatchClassName: "from-warning/40 via-warning/10 to-transparent" },
      { label: "Ocean", swatchClassName: "from-info/40 via-info/10 to-transparent" },
    ],
  },
  {
    id: "p02",
    slug: "grain-free-salmon-recipe",
    name: "Grain-Free Salmon Recipe",
    petType: "dogs",
    category: "Food & treats",
    price: 2899,
    rating: 4.9,
    reviewCount: 2310,
    badge: "Vet recommended",
    iconKey: "utensils",
    description:
      "Real salmon as the first ingredient, no fillers — formulated with a vet nutritionist for sensitive stomachs.",
    details: [
      { title: "Ingredients", content: "Salmon, sweet potato, peas, salmon oil (omega-3 & 6), no corn, wheat, or soy." },
      shippingReturns,
    ],
    inStock: true,
    rank: 2,
  },
  {
    id: "p03",
    slug: "interactive-puzzle-feeder",
    name: "Interactive Puzzle Feeder",
    petType: "dogs",
    category: "Toys & enrichment",
    price: 899,
    rating: 4.7,
    reviewCount: 856,
    iconKey: "gamepad",
    description:
      "Slows down fast eaters and keeps busy minds occupied — adjustable difficulty, dishwasher-safe.",
    details: [
      { title: "Care instructions", content: "Top-rack dishwasher safe. Air dry before refilling." },
      shippingReturns,
    ],
    inStock: true,
    rank: 5,
  },
  {
    id: "p04",
    slug: "adjustable-step-in-harness",
    name: "Adjustable Step-In Harness",
    petType: "dogs",
    category: "Gear & accessories",
    price: 1199,
    rating: 4.6,
    reviewCount: 512,
    badge: "New",
    iconKey: "shield",
    description:
      "No-pull, step-in design with reflective stitching — on in under 10 seconds, even with a wiggly dog.",
    details: [
      { title: "Sizing", content: "Adjustable chest strap, 5 sizes from XS to XL — see size guide for chest measurement." },
      shippingReturns,
    ],
    inStock: true,
    rank: 6,
  },
  {
    id: "p05",
    slug: "self-cleaning-litter-box",
    name: "Self-Cleaning Litter Box",
    petType: "cats",
    category: "Gear & accessories",
    price: 18999,
    originalPrice: 22999,
    rating: 4.7,
    reviewCount: 980,
    badge: "Bestseller",
    iconKey: "package",
    description:
      "Automatically rakes and seals waste into a sealed compartment — odor control that actually works.",
    details: [
      { title: "What's included", content: "Base unit, waste tray, 1 month of odor-control liners, power adapter." },
      shippingReturns,
    ],
    inStock: true,
    rank: 3,
    variants: [
      { label: "White", swatchClassName: "from-muted-foreground/30 via-muted-foreground/5 to-transparent" },
      { label: "Graphite", swatchClassName: "from-foreground/40 via-foreground/10 to-transparent" },
    ],
  },
  {
    id: "p06",
    slug: "grain-free-chicken-pate",
    name: "Grain-Free Chicken Pâté",
    petType: "cats",
    category: "Food & treats",
    price: 1499,
    rating: 4.8,
    reviewCount: 1420,
    iconKey: "utensils",
    description: "Single-source protein pâté, high moisture content to support hydration and urinary health.",
    details: [
      { title: "Ingredients", content: "Chicken, chicken broth, chicken liver, taurine — no by-products or artificial preservatives." },
      shippingReturns,
    ],
    inStock: true,
    rank: 7,
  },
  {
    id: "p07",
    slug: "feather-wand-teaser",
    name: "Feather Wand Teaser",
    petType: "cats",
    category: "Toys & enrichment",
    price: 349,
    rating: 4.5,
    reviewCount: 340,
    iconKey: "gamepad",
    description: "A wand toy built for real chase instinct — replaceable feather attachments included.",
    details: [
      { title: "What's included", content: "1 wand, 3 replaceable feather/fabric attachments." },
      shippingReturns,
    ],
    inStock: true,
    rank: 10,
  },
  {
    id: "p08",
    slug: "cozy-cave-cat-bed",
    name: "Cozy Cave Cat Bed",
    petType: "cats",
    category: "Beds & furniture",
    price: 1899,
    rating: 4.6,
    reviewCount: 610,
    iconKey: "home",
    description: "An enclosed, burrow-style bed for cats who feel safest when they're half-hidden.",
    details: [
      { title: "Materials", content: "Soft-shell exterior, faux-fur lining, machine washable on cold, air dry." },
      shippingReturns,
    ],
    inStock: false,
    rank: 11,
  },
  {
    id: "p09",
    slug: "vitamin-enriched-seed-mix",
    name: "Vitamin-Enriched Seed Mix",
    petType: "birds",
    category: "Food & treats",
    price: 549,
    rating: 4.4,
    reviewCount: 210,
    iconKey: "utensils",
    description: "A balanced seed and grain blend fortified with vitamins A, D3, and E for daily feeding.",
    details: [
      { title: "Ingredients", content: "Millet, canary grass seed, oats, sunflower seed, vitamin premix." },
      shippingReturns,
    ],
    inStock: true,
    rank: 12,
  },
  {
    id: "p10",
    slug: "foraging-wheel-toy",
    name: "Foraging Wheel Toy",
    petType: "birds",
    category: "Toys & enrichment",
    price: 799,
    rating: 4.6,
    reviewCount: 180,
    badge: "New",
    iconKey: "gamepad",
    description: "Hide treats in the spinning wheel to encourage natural foraging behavior and reduce boredom.",
    details: [
      { title: "Care instructions", content: "Wipe clean with a damp cloth. Not dishwasher safe." },
      shippingReturns,
    ],
    inStock: true,
    rank: 8,
  },
  {
    id: "p11",
    slug: "timothy-hay-bales",
    name: "Timothy Hay Bales (6-pack)",
    petType: "small-pets",
    category: "Food & treats",
    price: 699,
    rating: 4.9,
    reviewCount: 540,
    badge: "Bestseller",
    iconKey: "leaf",
    description: "Sun-cured, second-cut timothy hay — the everyday staple for rabbits, guinea pigs, and chinchillas.",
    details: [
      { title: "What's included", content: "6 compressed bales, ~1.5 lb each, resealable bag." },
      shippingReturns,
    ],
    inStock: true,
    rank: 4,
  },
  {
    id: "p12",
    slug: "wooden-chew-tunnel-set",
    name: "Wooden Chew & Tunnel Set",
    petType: "small-pets",
    category: "Toys & enrichment",
    price: 849,
    rating: 4.5,
    reviewCount: 190,
    iconKey: "gamepad",
    description: "All-natural wood tunnel and chew set that supports dental health while satisfying the urge to gnaw.",
    details: [
      { title: "Materials", content: "Untreated apple wood — safe for chewing, no glues or dyes." },
      shippingReturns,
    ],
    inStock: true,
    rank: 13,
  },
  {
    id: "p13",
    slug: "fleece-lined-hideaway",
    name: "Fleece-Lined Hideaway",
    petType: "small-pets",
    category: "Beds & furniture",
    price: 649,
    rating: 4.7,
    reviewCount: 260,
    iconKey: "home",
    description: "A snug fleece hideaway for burrowing, sleeping, and feeling safe in an open cage or hutch.",
    details: [
      { title: "Materials", content: "Anti-pill fleece exterior and lining, machine washable." },
      shippingReturns,
    ],
    inStock: true,
    rank: 14,
  },
  {
    id: "p14",
    slug: "adjustable-led-aquarium-light",
    name: "Adjustable LED Aquarium Light",
    petType: "aquatics",
    category: "Gear & accessories",
    price: 2499,
    rating: 4.6,
    reviewCount: 330,
    iconKey: "droplet",
    description: "Full-spectrum LED lighting with adjustable brightness and a built-in day/night timer.",
    details: [
      { title: "What's included", content: "Light unit, extendable mounting brackets, power adapter." },
      shippingReturns,
    ],
    inStock: true,
    rank: 9,
  },
  {
    id: "p15",
    slug: "water-conditioner-dechlorinator",
    name: "Water Conditioner & Dechlorinator",
    petType: "aquatics",
    category: "Health & wellness",
    price: 399,
    rating: 4.8,
    reviewCount: 470,
    badge: "Vet recommended",
    iconKey: "syringe",
    description: "Instantly neutralizes chlorine, chloramine, and heavy metals to make tap water safe for fish.",
    details: [
      { title: "Directions", content: "Add 1 capful per 10 gallons during water changes or new tank setup." },
      shippingReturns,
    ],
    inStock: true,
    rank: 15,
  },
  {
    id: "p16",
    slug: "aquatic-plant-starter-kit",
    name: "Aquatic Plant Starter Kit",
    petType: "aquatics",
    category: "Gear & accessories",
    price: 999,
    rating: 4.4,
    reviewCount: 150,
    iconKey: "leaf",
    description: "Three low-maintenance live plant species plus root tabs — an easy way to start a planted tank.",
    details: [
      { title: "What's included", content: "3 potted live plants (anubias, java fern, amazon sword), 5 root tabs." },
      shippingReturns,
    ],
    inStock: false,
    rank: 16,
  },
];
