import {
  BookOpen,
  Code2,
  Dumbbell,
  Scissors,
  Stethoscope,
  Users2,
  Utensils,
  type LucideIcon,
} from "lucide-react";
import type { Article, Author, FaqCategory, IconKey } from "./types";

export const blogIcons: Record<IconKey, LucideIcon> = {
  stethoscope: Stethoscope,
  utensils: Utensils,
  dumbbell: Dumbbell,
  scissors: Scissors,
  users: Users2,
  code: Code2,
  book: BookOpen,
};

export const categories = ["Vet care", "Nutrition", "Training", "Grooming", "Engineering"];

export const categoryIcons: Record<string, IconKey> = {
  "Vet care": "stethoscope",
  Nutrition: "utensils",
  Training: "dumbbell",
  Grooming: "scissors",
  Engineering: "code",
};

export const authors: Author[] = [
  {
    id: "au-01",
    slug: "naomi-cole",
    name: "Dr. Naomi Cole",
    title: "Veterinary contributor",
    bio: "Dr. Cole practices small animal medicine in Seattle and writes about everyday vet care for pet parents who'd rather not panic-Google symptoms at 2am.",
    initials: "NC",
    social: { twitter: "@drnaomicole" },
  },
  {
    id: "au-02",
    slug: "theo-alvarez",
    name: "Theo Alvarez",
    title: "Nutrition writer",
    bio: "Theo spent six years formulating pet food before switching to writing about it full-time — translating ingredient labels into plain English.",
    initials: "TA",
    social: { website: "theoalvarez.com" },
  },
  {
    id: "au-03",
    slug: "priya-menon",
    name: "Priya Menon",
    title: "Training & community lead",
    bio: "Priya runs PetZu's community forums and writes about training, behavior, and the occasional 2am panic post that turned out fine.",
    initials: "PM",
    social: { twitter: "@priyamenon" },
  },
  {
    id: "au-04",
    slug: "jordan-lee",
    name: "Jordan Lee",
    title: "Senior Engineer at PetZu",
    bio: "Jordan builds the systems behind PetZu's vet-matching and booking flows, and occasionally writes about how the sausage gets made.",
    initials: "JL",
    social: { website: "jordanlee.dev" },
  },
];

export const articles: Article[] = [
  {
    id: "ar-01",
    slug: "5-signs-your-dog-needs-a-vet-visit",
    title: "5 signs your dog needs a vet visit — not just a Google search",
    excerpt:
      "Vets weigh in on the symptoms that separate 'keep an eye on it' from 'come in today.'",
    category: "Vet care",
    tags: ["dogs", "health", "emergencies"],
    authorSlug: "naomi-cole",
    publishedAt: "2026-07-28",
    coverIconKey: "stethoscope",
    content: [
      { type: "paragraph", text: "Every dog owner has been there: it's 9pm, your dog is acting a little off, and you're three tabs deep into a symptom checker that's convinced you it's either nothing or a medical emergency. Vets see this exact panic constantly — so we asked a few what actually separates 'monitor at home' from 'come in now.'" },
      { type: "heading", level: 2, text: "1. Repeated vomiting within a few hours" },
      { type: "paragraph", text: "One vomiting episode after eating something questionable usually isn't an emergency. Three or more episodes within a few hours — especially with no food staying down — is a different story, particularly for puppies who dehydrate fast." },
      { type: "heading", level: 2, text: "2. A change in gum color" },
      { type: "paragraph", text: "Healthy gums are a light pink. Pale, white, or bluish gums can signal poor circulation or oxygen levels and warrant an urgent visit, not a wait-and-see approach." },
      { type: "quote", text: "Gum color is one of the fastest at-home checks that actually tells you something. Press gently, release, and the color should return within two seconds.", attribution: "Dr. Naomi Cole" },
      { type: "heading", level: 2, text: "3. Sudden lethargy that doesn't match the day" },
      { type: "paragraph", text: "Every dog has a low-energy day. The pattern to watch for is a sudden, out-of-character drop — a normally bouncy dog who won't get up for a walk, or a senior dog who's noticeably more withdrawn than their baseline." },
      { type: "heading", level: 2, text: "4. Straining without producing anything" },
      { type: "paragraph", text: "This applies to both ends. A dog repeatedly attempting to urinate or defecate without success — especially male dogs — can indicate a blockage, which is a genuine emergency, not a 'let's see how tomorrow goes' situation." },
      { type: "heading", level: 2, text: "5. Any suspected toxin exposure" },
      { type: "paragraph", text: "Chocolate, grapes, xylitol, certain plants, human medication — if there's a real chance of exposure, don't wait for symptoms. Call a vet or a pet poison hotline immediately; by the time symptoms show, treatment options can be more limited." },
      { type: "list", ordered: false, items: ["Keep your vet's after-hours number saved in your phone, not just Googled in the moment.", "A pet first-aid kit is worth the ₹20 it costs.", "When in doubt, a phone call to a vet costs you five minutes — a delayed visit can cost a lot more."] },
    ],
  },
  {
    id: "ar-02",
    slug: "kitten-nutrition-guide",
    title: "The complete guide to kitten nutrition, month by month",
    excerpt:
      "What to feed, how much, and when to transition — a feeding timeline vets actually recommend.",
    category: "Nutrition",
    tags: ["cats", "kittens", "nutrition"],
    authorSlug: "theo-alvarez",
    publishedAt: "2026-07-21",
    coverIconKey: "utensils",
    content: [
      { type: "paragraph", text: "Kitten nutrition changes faster than almost any other stage of pet care — a feeding plan that's right at 8 weeks is wrong by 6 months. Here's the timeline, broken down by what's actually changing developmentally." },
      { type: "heading", level: 2, text: "0–4 weeks: nursing (or a proper replacement)" },
      { type: "paragraph", text: "Kittens this young should be nursing. If you're hand-rearing an orphaned kitten, use a real kitten milk replacer — never cow's milk, which most kittens can't digest properly." },
      { type: "heading", level: 2, text: "4–8 weeks: the weaning window" },
      { type: "paragraph", text: "This is when solid food gets introduced gradually, usually as a gruel (kitten food mixed with warm water or replacer) before moving to drier textures. Expect a messy few weeks." },
      { type: "heading", level: 2, text: "2–6 months: peak growth, peak appetite" },
      { type: "paragraph", text: "Kittens in this window need roughly three times the calories per pound of an adult cat. This is not the phase to free-feed cautiously — kitten-formula food, offered generously, is appropriate here." },
      { type: "heading", level: 2, text: "6–12 months: the transition to adult food" },
      { type: "paragraph", text: "Growth slows but doesn't stop. Most cats can transition to adult food around 12 months, though large breeds (Maine Coons especially) may benefit from staying on kitten formula slightly longer." },
      { type: "list", ordered: true, items: ["Always transition foods gradually over 5–7 days to avoid stomach upset.", "Fresh water matters as much as food — especially for cats who don't drink much.", "If a kitten stops eating for more than 24 hours, that's a vet visit, not a wait-it-out."] },
    ],
  },
  {
    id: "ar-03",
    slug: "how-to-choose-pet-insurance",
    title: "How to actually choose a pet insurance plan",
    excerpt:
      "The fine print that matters, the questions to ask, and what most plans quietly exclude.",
    category: "Vet care",
    tags: ["insurance", "guides"],
    authorSlug: "naomi-cole",
    publishedAt: "2026-07-14",
    coverIconKey: "stethoscope",
    content: [
      { type: "paragraph", text: "Pet insurance marketing tends to lead with the reassuring parts and bury the exclusions. Here's what actually matters when comparing plans." },
      { type: "heading", level: 2, text: "Pre-existing conditions aren't covered — but the definition varies" },
      { type: "paragraph", text: "Every insurer excludes pre-existing conditions. What varies is how strictly they define 'pre-existing' — some permanently exclude a body system after one related visit, others only exclude the specific diagnosed condition." },
      { type: "heading", level: 2, text: "Check the reimbursement model, not just the premium" },
      { type: "paragraph", text: "A cheap plan with an 70% reimbursement rate and a ₹1,000 deductible can cost you more out-of-pocket during an actual emergency than a pricier plan with 90% reimbursement and a ₹250 deductible. Model an actual ₹3,000 emergency against both." },
      { type: "heading", level: 2, text: "Wellness add-ons are usually a separate math problem" },
      { type: "paragraph", text: "Routine wellness coverage (vaccines, annual exams) is often an add-on with its own cap. Compare the add-on's annual cost against what you'd actually spend on routine care without it — sometimes it pencils out, sometimes it doesn't." },
      { type: "quote", text: "Ask an insurer directly: 'If my dog tears an ACL at age 6, walk me through exactly what's covered and what isn't.' Their answer tells you more than any brochure.", attribution: "Dr. Naomi Cole" },
    ],
  },
  {
    id: "ar-04",
    slug: "positive-reinforcement-training-guide",
    title: "Positive reinforcement training: a beginner's guide",
    excerpt: "The core mechanics behind reward-based training, and why timing matters more than treats.",
    category: "Training",
    tags: ["dogs", "training", "behavior"],
    authorSlug: "priya-menon",
    publishedAt: "2026-07-07",
    coverIconKey: "dumbbell",
    content: [
      { type: "paragraph", text: "Positive reinforcement training gets reduced to 'give treats for good behavior' a lot, which undersells what's actually happening. The mechanic that matters most isn't the reward itself — it's the timing." },
      { type: "heading", level: 2, text: "Mark the behavior, then reward it" },
      { type: "paragraph", text: "A marker — a clicker, or a consistent word like 'yes' — tells your dog the exact instant they did the right thing, before the treat even arrives. Without a marker, a two-second delay between behavior and treat can accidentally reward whatever happened in between." },
      { type: "heading", level: 2, text: "Consistency beats intensity" },
      { type: "paragraph", text: "Five minutes of focused training, done daily, outperforms one exhausting hour-long session on the weekend. Dogs build reliable behavior through repetition spaced over time, not cramming." },
      { type: "heading", level: 2, text: "Fade the treats, don't drop them" },
      { type: "paragraph", text: "Once a behavior is reliable, shift from rewarding every repetition to rewarding intermittently — this is what actually makes a behavior 'stick' long-term, rather than falling apart the moment treats disappear entirely." },
      { type: "list", ordered: false, items: ["Keep training sessions short enough that your dog stays engaged, not bored.", "Reward the behavior you want to see more of — ignoring unwanted behavior is often more effective than correcting it.", "Every dog learns at a different pace; comparing your dog's timeline to another dog's is the fastest way to get frustrated."] },
    ],
  },
  {
    id: "ar-05",
    slug: "grooming-double-coated-dogs",
    title: "Grooming your double-coated dog: a seasonal guide",
    excerpt: "Why shaving a double coat usually backfires, and what to do instead through shedding season.",
    category: "Grooming",
    tags: ["dogs", "grooming", "shedding"],
    authorSlug: "priya-menon",
    publishedAt: "2026-06-30",
    coverIconKey: "scissors",
    content: [
      { type: "paragraph", text: "Double-coated breeds — Huskies, Golden Retrievers, German Shepherds — have a dense undercoat under a longer guard coat, and shedding season means both layers are in flux at once. The most common grooming mistake is reaching for clippers." },
      { type: "heading", level: 2, text: "Why shaving usually backfires" },
      { type: "paragraph", text: "The guard coat actually helps regulate temperature and protects skin from sun exposure. Shaving it off doesn't reliably grow back the same way, and can leave a dog more vulnerable to sunburn and overheating — the opposite of the intended effect." },
      { type: "heading", level: 2, text: "De-shedding, not de-coating" },
      { type: "paragraph", text: "A proper undercoat rake or de-shedding tool, used regularly through shedding season, removes the loose undercoat without touching the protective guard coat. It's more work than a single shave, but it's the version that actually works." },
      { type: "gallery", images: [
        { caption: "Undercoat rake — for the dense layer underneath", iconKey: "scissors" },
        { caption: "Slicker brush — for the topcoat between sessions", iconKey: "scissors" },
        { caption: "De-shedding comb — fine teeth for finishing", iconKey: "scissors" },
      ] },
      { type: "heading", level: 2, text: "A realistic seasonal rhythm" },
      { type: "paragraph", text: "Twice-weekly brushing outside of shedding season, ramping up to daily during the two heaviest shedding windows (typically spring and fall) — bathing before a big de-shedding session also loosens the undercoat and makes the whole process faster." },
    ],
  },
  {
    id: "ar-06",
    slug: "how-we-built-vet-matching",
    title: "Inside PetZu: how we match you with the right vet",
    excerpt: "A behind-the-scenes look at the scoring system that ranks vet search results.",
    category: "Engineering",
    tags: ["engineering", "product"],
    authorSlug: "jordan-lee",
    publishedAt: "2026-06-23",
    coverIconKey: "code",
    content: [
      { type: "paragraph", text: "When you search for a vet on PetZu, the results aren't sorted by distance alone, or by rating alone — they're ranked by a weighted score that tries to approximate what actually matters to you. Here's a simplified version of how it works." },
      { type: "heading", level: 2, text: "The scoring inputs" },
      { type: "paragraph", text: "Four signals feed the score: rating, review volume (a 5.0 from 3 reviews shouldn't outrank a 4.8 from 800), distance, and whether the provider is currently accepting new patients. Each gets normalized to a 0–1 range before weighting." },
      { type: "code", language: "typescript", filename: "score-provider.ts", code: "interface ScoringInput {\n  rating: number; // 0-5\n  reviewCount: number;\n  distanceMiles: number;\n  acceptingNewPatients: boolean;\n}\n\nfunction scoreProvider(input: ScoringInput): number {\n  const ratingScore = input.rating / 5;\n  const volumeConfidence = Math.min(input.reviewCount / 200, 1);\n  const distanceScore = 1 - Math.min(input.distanceMiles / 25, 1);\n  const availabilityBoost = input.acceptingNewPatients ? 1 : 0.4;\n\n  return (\n    ratingScore * 0.4 +\n    volumeConfidence * 0.2 +\n    distanceScore * 0.25 +\n    availabilityBoost * 0.15\n  );\n}" },
      { type: "heading", level: 2, text: "Why review volume gets its own weight" },
      { type: "paragraph", text: "A perfect rating with almost no reviews is a weaker signal than a slightly lower rating with hundreds — the `volumeConfidence` term prevents a brand-new, unreviewed profile from ever accidentally outranking an established, trusted one on rating alone." },
      { type: "heading", level: 2, text: "What this doesn't do (yet)" },
      { type: "paragraph", text: "This version doesn't personalize based on your own search history or the specialties you've searched for before — that's a reasonable next iteration, but it adds a cold-start problem we haven't solved cleanly yet." },
    ],
  },
  {
    id: "ar-07",
    slug: "reading-pet-food-labels",
    title: "A guide to reading pet food labels",
    excerpt: "Ingredient order, guaranteed analysis, and the marketing terms that don't mean what they imply.",
    category: "Nutrition",
    tags: ["nutrition", "guides"],
    authorSlug: "theo-alvarez",
    publishedAt: "2026-06-16",
    coverIconKey: "utensils",
    content: [
      { type: "paragraph", text: "Pet food labels are legally regulated, which means there's more real information on them than the marketing suggests — you just have to know where to look." },
      { type: "heading", level: 2, text: "Ingredients are listed by pre-cooking weight" },
      { type: "paragraph", text: "This is the single most misleading part of a label. 'Fresh chicken' listed first sounds great, but raw chicken is roughly 70% water — once cooked, it may weigh less than the grain listed second. Weight order isn't nutrient order." },
      { type: "heading", level: 2, text: "The guaranteed analysis is a floor and ceiling, not a fact sheet" },
      { type: "paragraph", text: "Guaranteed analysis gives you minimums for protein and fat, and maximums for fiber and moisture — not exact values. Two foods with identical guaranteed analysis numbers can still have meaningfully different actual nutrient content." },
      { type: "heading", level: 2, text: "Terms that sound regulated but mostly aren't" },
      { type: "paragraph", text: "\"Premium,\" \"gourmet,\" and \"natural\" have little to no legal definition in most regions. \"Complete and balanced,\" by contrast, is a real regulated claim tied to meeting specific nutrient profiles — that's the phrase actually worth looking for." },
      { type: "list", ordered: false, items: ["Look for an AAFCO (or regional equivalent) nutritional adequacy statement — that's the real substance behind a label.", "\"By-product\" isn't inherently bad — organ meat is a by-product and is often more nutrient-dense than muscle meat.", "If in doubt, a vet nutritionist consult is worth it for pets with specific health conditions."] },
    ],
  },
];

export const faqCategories: FaqCategory[] = [
  {
    title: "General",
    items: [
      { question: "What is The PetZu World?", answer: "PetZu is a platform for pet parents — shop vetted products, book vets and groomers, and read care guides, all in one place." },
      { question: "Is PetZu available in my city?", answer: "PetZu currently operates in 85+ cities, with same-day delivery in most of them. Enter your ZIP code at checkout to confirm coverage in your area." },
      { question: "Do I need an account to browse?", answer: "No — you can browse products, providers, and articles without an account. You'll need one to check out or book an appointment." },
    ],
  },
  {
    title: "Orders & shipping",
    items: [
      { question: "How fast is delivery?", answer: "Most orders arrive within 2–5 business days. Same-day delivery is available in 85+ cities for orders placed before 2pm local time." },
      { question: "What's your return policy?", answer: "Unopened products can be returned within 30 days for a full refund. Opened food and treats are handled case-by-case for safety reasons — contact support." },
      { question: "Can I change my order after placing it?", answer: "Orders can be modified within 30 minutes of placing them. After that, they've usually already entered fulfillment — contact support and we'll do what we can." },
    ],
  },
  {
    title: "Vet booking",
    items: [
      { question: "Are the vets on PetZu licensed?", answer: "Yes — every vet on the platform is licensed and verified before their profile goes live, and re-verified periodically." },
      { question: "Can I book a same-day appointment?", answer: "Many providers offer same-day video consults; in-clinic availability depends on the individual provider's calendar, shown on their profile." },
      { question: "What if I need to cancel or reschedule?", answer: "You can reschedule or cancel from your booking confirmation up to 4 hours before the appointment without a fee." },
    ],
  },
  {
    title: "Grooming",
    items: [
      { question: "Do groomers come to my home?", answer: "Some do — look for the \"Mobile grooming\" specialty tag on a provider's profile to filter for in-home service." },
      { question: "How do I know what breed-specific style I'm getting?", answer: "You can leave style notes when booking, and most groomers offer a quick consult call for breeds with more particular cuts." },
    ],
  },
];
